version: '3'
services:
  mongo:
    image: mongo:5.0
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db

  mongoku:
    image: huggingface/mongoku:latest
    depends_on:
      - mongo
    ports:
      - '3100:3100'
    environment:
      - 'MONGOKU_DEFAULT_HOST=mongodb://mongo:27017'
    links:
      - mongo

  gameserver:
    image: tf2pickuppl/tf2-gameserver:latest
    environment:
      - 'RCON_PASSWORD=123456'
      - 'TF2PICKUPORG_API_ADDRESS=127.0.0.1:3000'
      - 'TF2PICKUPORG_SECRET=xxxxxx'
    network_mode: host
    stdin_open: true
    tty: true

volumes:
  mongodb:
