name: test

on:
  push:
    branches:
      - 'master'
      - '*.*.*'
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - 'master'

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Test
      run: npm run test:ci

    - name: Build
      run: npm run build

    - name: Upload test coverage info
      uses: codecov/codecov-action@v1

  e2e-tests:
    runs-on: ubuntu-latest
    needs: [unit-tests]

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start services
      run: docker-compose up -d

    - name: Sleep for 30 seconds # let TF2 server boot up properly
      uses: jakejarvis/wait-action@v0.1.0
      with:
        time: '30s'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: |
        export MONGODB_HOST=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' server_mongo_1)
        export MONGODB_PORT=27017
        export MONGODB_DB=tf2pickuppl_e2e_tests
        npm run test:e2e

    - name: Stop services
      run: docker-compose down
