name: test

on:
  push:
    branches:
      - 'master'
      - '*.*.*'
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - 'master'

jobs:
  unit-tests:
    name: unit
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.8.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: yarn

    - name: Install dependencies
      run: yarn install --immutable

    - name: Run unit test
      run: yarn test:ci

    - name: Upload test coverage info
      uses: codecov/codecov-action@v2

  e2e-tests:
    name: end-to-end
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.8.x]

    services:
      mongo:
        image: mongo:4.0
        ports:
          - 27017:27017

      gameserver:
        image: tf2pickuppl/tf2-gameserver
        ports:
          - 27015:27015/tcp
          - 27015:27015/udp
          - 27020:27020/udp
        env:
          RCON_PASSWORD: '123456'
          TF2PICKUPORG_API_ADDRESS: 'host.docker.internal:3000'
          TF2PICKUPORG_SECRET: 'xxxxxx'
        options: --tty --add-host host.docker.internal:host-gateway

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: yarn

    - name: Install dependencies
      run: yarn install --immutable

    - name: Run e2e tests
      env:
        API_URL: 'http://localhost:3000'
        CLIENT_URL: 'http://localhost:4200'
        BOT_NAME: 'tf2pickup.pl'
        MONGODB_URI: 'mongodb://localhost:27017/tf2pickuppl_e2e_tests'
        STEAM_API_KEY: 'FAKE_API_KEY'
        KEY_STORE_PASSPHARE: 'a_password'
        SUPER_USER: '76561199195756652'
        QUEUE_CONFIG: '6v6'
        MUMBLE_SERVER_URL: 'melkor.tf'
        MUMBLE_CHANNEL_NAME: 'tf2pickup'
        LOG_RELAY_ADDRESS: 'host.docker.internal'
        LOG_RELAY_PORT: '9871'
        GAME_SERVER_SECRET: 'xxxxxx'
      run: yarn test:e2e

    - name: Upload test coverage info
      uses: codecov/codecov-action@v2

  build:
    name: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.8.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn install --immutable

    - name: Build
      run: yarn build
